### ISSUE TITLE
E-commerce Checklist

### ISSUE THREAD

**Issue by pnalexander** [pnalexander/refab_v2#112]
### Individual Listings ###
- [ ] Thumbnail Image
- [ ] Product Name
- [ ] Collection Name
- [ ] Vertical Ellipses (opens Listing Brief)
- [ ] Listing Brief
  - [ ] Product Name
  - [ ] Short Description
  - [ ] View Item (link to listing)
  - [ ] Price (per unit + processing surcharge)

### Functions ###
- [ ] Sort Listings
  - [ ] Show All
  - [ ] By Collection
  - [ ] By Use (maybe switch up to by type - e.g. tables, desks, chairs, etc.)

---

### Above the Fold ###
- [ ] Large, high quality attention-grabbing photo
- [ ] Product Name
- [ ] Collection & Category
- [ ] Price (starting at + processing surcharge)
- [ ] Short Description
- [ ] Add to Cart (button)
- [ ] Enlargeable thumbnails (minimum 3 photos)
- [ ] Information Tabs

### Information Tabs ###
- [ ] Overview
  - [ ] Long Description (formatted)
- [ ] Dimensions
  - [ ] Standard dimensions table
  - [ ] Highlight shown dimension set
- [ ] Optionals
  - [ ] Stain Choice
  - [ ] Sheen Choice
  - [ ] Alternate Edge Detail Choice
  - [ ] Metal paint color
  - [ ] Power Modules
- [ ] Specs & Docs
  - [ ] Product-Specific Brochure
  - [ ] Assembly Instructions
  - [ ] Materials & Color Reference
  - [ ] Furniture Specification (potentially only available to registered clients)

### Functions ###
- [ ] Add to Cart
- [ ] Customize Item (based on Optionals from Info Tabs)
  - [ ] Stain(s) selection
  - [ ] Sheen selection
  - [ ] Edge Detail selection
  - [ ] Metal Paint Color selection
  - [ ] Additionals (hardware,power, cable management, etc.)
- [ ] Impromptu Shopping Cart
- [ ] Thumbnail Enhancement
  - [ ] Click to enlarge
- [ ] Gallery
  - [ ] Cycle through photo gallery
