### ISSUE TITLE
Variations V1 Remaining Checklist

### ISSUE THREAD

**Issue by pnalexander** [pnalexander/refab_v2#119]
- [x] Remove From Cart (delete cart_item_variations with associated cart_contents_id)
- [x] Adjusted or Processed Pricing needs to carryover from product page to cart page
- [x] Adjusted or Processed Pricing needs to carryover throughout checkout until transaction is complete
- [x] Selected Variations need to be visible after an item is added to a cart
- [x] Display Variation Swatches on item card in cart and order summary
  - [x] Dimensions
  - [x] Primary Finish Sample
  - [x] Secondary Finish Sample
